/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ApiFn": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Auth": {
      "type": "sst.aws.Router"
      "url": string
    }
    "AuthFn": {
      "publicKey": string
      "type": "sst.aws.Auth"
    }
    "AuthFnAuthenticator": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Database": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Email": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "Frontend": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
    "Router": {
      "type": "sst.aws.Router"
      "url": string
    }
    "Storage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
